# Periodically check the command list to see if new commands were added?
Periodically-Check: false

# How often should the command list be checked for new commands (in seconds)
Interval: 60

# Should all commands with ":" be disabled?
Disable-All-Prefixes: true

# Prefixes that should be disabled (or enabled if Disable-All-Prefixes is true)
Prefixes:
  - minecraft