name: "NoCommandPrefixes"
description: "Disables the commands with fallback prefixes."
website: "https://mrzcookie.com"
authors:
  - "MrZCookie"
  - "Pyr#6969"

main: "com.mrzcookie.nocommandprefixes.FallbackRemoverPlugin"
version: "${project.version}"
api-version: "1.13"

commands:
  reloadfallbackremover:
    aliases: ["reloadfb"]
    permission: "fallbackremover.reload"
